# Generated by Django 5.2 on 2025-04-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='title',
            new_name='text',
        ),
    ]
